# Generated by Django 5.1 on 2024-10-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_passenger_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField(unique=True)),
                ('train_name', models.CharField(unique=True)),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('coaches', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('train_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.BigIntegerField()),
                ('seat_no', models.IntegerField()),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField()),
                ('waiting_no', models.IntegerField()),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.passenger_register')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Train_fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='App.stations')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='App.stations')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_id', models.BigIntegerField()),
                ('train_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.train_fare')),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('refund_amount', models.FloatField()),
                ('deduction', models.FloatField()),
                ('booking_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking')),
                ('train_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.train_fare')),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_no', models.IntegerField()),
                ('train_time', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.stations')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trains')),
            ],
        ),
    ]
