# Generated by Django 5.1 on 2024-10-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='train_name',
            field=models.CharField(),
        ),
    ]
