# Generated by Django 5.1 on 2024-10-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_trains_train_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforms',
            old_name='station',
            new_name='station_name',
        ),
    ]
