# Generated by Django 5.1 on 2024-10-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_station_platforms_station_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforms',
            old_name='station_name',
            new_name='station_namee',
        ),
    ]
