# Generated by Django 5.1 on 2024-10-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_station_name_platforms_station_namee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforms',
            old_name='station_namee',
            new_name='station_name',
        ),
    ]
