# Generated by Django 5.1 on 2024-10-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_train_platforms_train_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='train_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
