# Generated by Django 5.1 on 2024-10-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_platforms_train_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platforms',
            name='train_name',
        ),
    ]
