# Generated by Django 5.1 on 2024-10-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_station_name_platforms_station_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforms',
            old_name='station_names',
            new_name='station_name',
        ),
        migrations.RenameField(
            model_name='platforms',
            old_name='train_names',
            new_name='train_name',
        ),
        migrations.RenameField(
            model_name='train_fare',
            old_name='train',
            new_name='train_name',
        ),
    ]
