# Generated by Django 5.1 on 2024-10-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_station_names_platforms_station_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platforms',
            name='train_no',
        ),
    ]
