# Generated by Django 5.1 on 2024-10-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_platforms_train_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='train_time',
            field=models.CharField(),
        ),
    ]
