# Generated by Django 5.1 on 2024-10-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_trains_running_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.CharField(),
        ),
    ]
