# Generated by Django 5.1 on 2024-10-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_booking_booking_time_alter_booking_seat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_fare',
            name='from_station',
        ),
        migrations.RemoveField(
            model_name='train_fare',
            name='to_station',
        ),
    ]
